name: 'Actions SemVer Checker'
description: 'Checks the version tags for your action repository to ensure the correct versions will be picked.'
branding:
  icon: 'check-circle'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: "Checking versions..."
      run: |
        & $env:GITHUB_ACTION_PATH/main.ps1
      shell: pwsh
